# Generated by Django 6.0.3 on 2026-03-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0003_item_latitude_item_longitude_claimrequest_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_sensitive',
        ),
        migrations.RemoveField(
            model_name='item',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='item',
            name='longitude',
        ),
    ]
