# Generated by Django 6.0.3 on 2026-04-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0004_remove_item_is_sensitive_remove_item_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('PERSONAL', 'Personal'), ('ELECTRONICS', 'Electronics'), ('DOCUMENTS', 'Documents'), ('CLOTHING', 'Clothing'), ('ACADEMIC', 'Academic'), ('VALUABLE', 'Valuable'), ('MISC', 'Miscellaneous')], db_index=True, default='MISC', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('LOST', 'Lost'), ('FOUND', 'Found'), ('CLAIMED', 'Claimed')], db_index=True, default='LOST', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
