# Generated by Django 6.0.3 on 2026-04-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0005_message_is_read_alter_claimrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='item_thumbnails/'),
        ),
    ]
